# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[Languages.de.main]]
    name = "Home"
    identifier = "about"
    url = "#about"
    weight = 10

[[Languages.de.main]]
    name = "Artikel"
    identifier = "posts"
    url = "#posts"
    weight = 20

[[Languages.de.main]]
    name = "Projekte"
    identifier = "projects"
    url = "#projects"
    weight = 30

[[Languages.de.main]]
    name = "Kontakt/Impressum"
    identifier = "contact"
    url = "#contact"
    weight = 60

[[Languages.en.main]]
    name = "Home"
    identifier = "about"
    url = "#about"
    weight = 10


[[Languages.en.main]]
    name = "Posts"
    identifier = "posts"
    url = "#posts"
    weight = 20


[[Languages.en.main]]
    name = "Projects"
    identifier = "projects"
    url = "#projects"
    weight = 30

[[Languages.en.main]]
    name = "Contact/Imprint"
    identifier = "contact"
    url = "#contact"
    weight = 60

# [[languages.de.main]]
#   name = "Veröffentlichungen"
#   identifier = "featured"
#   url = "#featured"
#   weight = 40

# [[languages.en.main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40





# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
